export const staticPolls = [
  {
    id: "1",
    title: "What is your favorite programming language?",
    description: "Choose the language you enjoy the most.",
    options: [
      { id: "1", text: "JavaScript" },
      { id: "2", text: "Python" },
      { id: "3", text: "TypeScript" },
      { id: "4", text: "Go" },
    ],
    user_id: "static",
    is_public: true,
    allow_multiple_votes: false,
    require_login_to_vote: false,
    ends_at: null,
    created_at: new Date().toISOString(),
    votes_count: 120,
    registered_votes_count: 80,
    anonymous_votes_count: 40,
  },
  {
    id: "2",
    title: "Which front-end framework do you prefer?",
    description: "Select the framework you like to work with.",
    options: [
      { id: "5", text: "React" },
      { id: "6", text: "Vue" },
      { id: "7", text: "Angular" },
      { id: "8", text: "Svelte" },
    ],
    user_id: "static",
    is_public: true,
    allow_multiple_votes: true,
    require_login_to_vote: false,
    ends_at: null,
    created_at: new Date().toISOString(),
    votes_count: 250,
    registered_votes_count: 150,
    anonymous_votes_count: 100,
  },
];
